export const ADVANCED_FILTER_DEFAULTS = {
  businessUnit: '',
  cardNumber: '',
  cardAssignedTo: '',
  status: '',
  typeOfService: '',
  serviceHandler: '',
  costCenter: '',
  approvedBy: '',
  recurring: '',
  startDate: '',
  endDate: '',
  disableStartDate: '',
  disableEndDate: '',
  month: '',
  minAmount: '',
  maxAmount: '',
  duplicateStatus: '',
  sharedOnly: '',
};
